cate_small_reset_dict = {
    'music': ['music'],
    'lifestyle': ['lifestyle'],
    'autos': ['auto'],
    'middleeast': ['middleeast'],
    'games': ['game'],
    'movies': ['movie'],
    'northamerica': ['northamerica'],
    'weather': ['weather'],
    'sports': ['sport'],
    'travel': ['travel'],
    'tv': ['TV'],
    'finance': ['finance'],
    'foodanddrink': ['food', 'and', 'drink'],
    'kids': ['kid'],
    'video': ['video'],
    'health': ['health'],
    'news': ['news'],
    'entertainment': ['entertainment']
}



subcate_small_reset_dict = {
    'ads-latingrammys': ['ads', 'latin', 'grammy'],
    'comedy': ['comedy'],
    'finance-real-estate': ['finance', 'real-estate'],
    'football_nfl_videos': ['football', 'NFL', 'video'],
    'humor': ['humor'],
    'lifestylerelationships': ['lifestyle', 'relationship'],
    'causes-poverty': ['cause', 'poverty'],
    'autosenthusiasts': ['auto', 'enthusiast'],
    'lifestylelovesex': ['lifestyle', 'love', 'sex'],
    'entertainmentmusic': ['entertainment', 'music'],
    'finance-companies': ['finance', 'company'],
    'golfvideos': ['golf', 'video'],
    'fitness': ['fitness'],
    'animals': ['animal'],
    'relationships': ['relationship'],
    'newsscience': ['news', 'science'],
    'wines': ['wine'],
    'empowering-the-planet': ['empowering', 'the', 'planet'],
    'topnews': ['top', 'news'],
    'basketball_nba': ['basketball', 'NBA'],
    'movies-awards': ['movie', 'award'],
    'foodtips': ['food', 'tip'],
    'newsus': ['news', 'US'],
    'finance-small-business': ['finance', 'small', 'business'],
    'finance-insurance': ['finance', 'insurance'],
    'finance-education': ['finance', 'education'],
    'shop-computers-electronics': ['shop', 'computer', 'electronic'],
    'lifestyletravel': ['lifestyle', 'travel'],
    'finance-billstopay': ['finance', 'bill', 'to', 'pay'],
    'lifestyleshoppinghomegarden': ['lifestyle', 'shopping', 'home', 'garden'],
    'lifestylestyle': ['lifestyle', 'style'],
    'finance-healthcare': ['finance', 'healthcare'],
    'autosluxury': ['auto', 'luxury'],
    'cookingschool': ['cooking', 'school'],
    'newsvideo': ['news', 'video'],
    'video': ['video'],
    'newsrealestate': ['news', 'real-estate'],
    'retirement': ['retirement'],
    'technologyinvesting': ['technology', 'investing'],
    'newsphotos': ['news', 'photo'],
    'lifestylecareer': ['lifestyle', 'career'],
    'newsoffbeat': ['news', 'offbeat'],
    'shop-home-goods': ['shop', 'home', 'goods'],
    'lifestylevideo': ['lifestyle', 'video'],
    'othersports': ['other', 'sport'],
    'spendingandborrowing': ['spending', 'and', 'borrowing'],
    'foodanddrink': ['food', 'and', 'drink'],
    'celebrity': ['celebrity'],
    'newsbusiness': ['news', 'business'],
    'causes-food-insecurity': ['cause', 'food', 'insecurity'],
    'racing': ['racing'],
    'lifestyleanimals': ['lifestyle', 'animal'],
    'yearinoffbeatgoodnews': ['year', 'in', 'offbeat', 'good', 'news'],
    'cma-awards': ['CMA', 'award'],
    'wellness': ['wellness'],
    'lifestylepets': ['lifestyle', 'pet'],
    'music-gallery': ['music', 'gallery'],
    'autostokyo': ['auto', 'tokyo'],
    'entertainment-books': ['entertainment', 'book'],
    'soccer': ['soccer'],
    'tv-reviews': ['TV', 'review'],
    'news': ['news'],
    'wonder': ['wonder'],
    'indepth': ['indepth'],
    'elections-2020-us': ['elections', '2020', 'US'],
    'autoslosangeles': ['auto', 'los-angeles'],
    'travel-points-rewards': ['travel', 'point', 'reward'],
    'finance-taxes': ['finance', 'tax'],
    'music-grammys': ['music', 'grammy'],
    'pregnancyparenting': ['pregnancy', 'parenting'],
    'finance-career-education': ['finance', 'career', 'education'],
    'career-news': ['career', 'news'],
    'viral': ['viral'],
    'newstvmedia': ['news', 'TV', 'media'],
    'awardstyle': ['award', 'style'],
    'lifestylediy': ['lifestyle', 'DIY'],
    'newsother': ['news', 'other'],
    'football_nfl': ['football', 'NFL'],
    'movievideo': ['movie', 'video'],
    'basketball_ncaa_videos': ['basketball', 'NCAA', 'video'],
    'autosnews': ['auto', 'news'],
    'autosresearchguides': ['auto', 'research', 'guide'],
    'finance-startinvesting': ['finance', 'start', 'investing'],
    'celebhub': ['celeb', 'hub'],
    'movies-celebrity': ['movie', 'celebrity'],
    'finance-technology': ['finance', 'technology'],
    'football_ncaa_videos': ['football', 'NCAA', 'video'],
    'healthnews': ['health', 'news'],
    'newsworldpolitics': ['news', 'world', 'politics'],
    'company-news': ['company', 'news'],
    'newsgoodnews': ['news', 'good', 'news'],
    'science': ['science'],
    'sports': ['sport'],
    'financenews': ['finance', 'news'],
    'lifestyleweddings': ['lifestyle', 'wedding'],
    'newspolitics': ['news', 'politics'],
    'advice': ['advice'],
    'travelarticle': ['travel', 'article'],
    'cocktails': ['cocktail'],
    'finance-mutual-funds': ['finance', 'mutual', 'fund'],
    'music-awards': ['music', 'award'],
    'newsweather': ['news', 'weather'],
    'mentalhealth': ['mental', 'health'],
    'weatherfullscreenmaps': ['weather', 'full', 'screen', 'map'],
    'lifestylecelebstyle': ['lifestyle', 'celeb', 'style'],
    'autossuvs': ['auto', 'SUV'],
    'mma': ['MMA'],
    'games': ['game'],
    'health-cancer': ['health', 'cancer'],
    'tv-recaps': ['TV', 'recap'],
    'newsopinion': ['news', 'opinion'],
    'lifestylemindandsoul': ['lifestyle', 'mind', 'and', 'soul'],
    'popculture': ['pop', 'culture'],
    'entertainment-celebrity': ['entertainment', 'celebrity'],
    'autossports': ['auto', 'sport'],
    'finance-homesandpropertysection': ['finance', 'home', 'and', 'property', 'section'],
    'traveltips': ['travel', 'tip'],
    'holidays': ['holiday'],
    'newstechnology': ['news', 'technology'],
    'lifestylecleaningandorganizing': ['lifestyle', 'cleaning', 'and', 'organizing'],
    'foodrecipes': ['food', 'recipe'],
    'autosbuying': ['auto', 'buying'],
    'outdoors': ['outdoor'],
    'lifestylepetsanimals': ['lifestyle', 'pet', 'animal'],
    'fun': ['fun'],
    'medical': ['medical'],
    'traveltripideas': ['travel' ,'trip', 'idea'],
    'middleeast-top-stories': ['middleeast', 'top', 'story'],
    'restaurantsandnews': ['restaurant', 'and', 'news'],
    'golf': ['golf'],
    'lifestylebuzz': ['lifestyle', 'buzz'],
    'lifestylefamily': ['lifestyle', 'family'],
    'finance-home-loans': ['finance', 'home', 'loan'],
    'movies-oscars': ['movie', 'Oscars'],
    'lifestyleparenting': ['lifestyle', 'parenting'],
    'travel-videos': ['travel', 'video'],
    'finance-credit': ['finance', 'credit'],
    'basketball_wnba': ['basketball', 'WNBA'],
    'factcheck': ['factcheck'],
    'lifestylewhatshot': ['lifestyle', 'whats', 'hot'],
    'tv-celebrity': ['TV', 'celebrity'],
    'music-celebrity': ['music', 'celebrity'],
    'mmaufc': ['MMA', 'UFC'],
    'newsworld': ['news', 'world'],
    'musicnews': ['music', 'news'],
    'autosresearch': ['auto', 'research'],
    'autossema': ['auto', 'SEMA'],
    'northamerica-video': ['northamerica', 'video'],
    'finance-retirement': ['finance', 'retirement'],
    'causes-military-appreciation': ['cause', 'military', 'appreciation'],
    'healthagingwell': ['health', 'aging', 'well'],
    'tv': ['TV'],
    'markets': ['market'],
    'autoscompact': ['auto', 'compact'],
    'travel': ['travel'],
    'icehockey_nhl': ['ice', 'hockey', 'NHL'],
    'shop-holidays': ['shop', 'holiday'],
    'shop-books-movies-tv': ['shop', 'book', 'movie', 'TV'],
    'newselection2020': ['news', 'election', '2020'],
    'lifestylehoroscope': ['lifestyle', 'horoscope'],
    'tvnews': ['TV', 'news'],
    'newsscienceandtechnology': ['news', 'science', 'and', 'technology'],
    'finance-top-stocks': ['finance', 'top', 'stock'],
    'quickandeasy': ['quick', 'and', 'easy'],
    'autosclassics': ['auto', 'classic'],
    'autostrucks': ['auto', 'truck'],
    'autosvans': ['auto', 'van'],
    'strength': ['strength'],
    'causes': ['cause'],
    'videos': ['video'],
    'soccer_bund': ['soccer', 'bund'],
    'beverages': ['beverage'],
    'newsfactcheck': ['news', 'factcheck'],
    'reviews': ['review'],
    'games-news': ['game', 'news'],
    'photos': ['photo'],
    'autosmidsize': ['auto', 'midsize'],
    'lifestyledecor': ['lifestyle', 'decor'],
    'baseball_mlb': ['baseball', 'MLB'],
    'weathertopstories': ['weather', 'top', 'story'],
    'tennis_intl': ['tennis', 'INTL'],
    'hollywood': ['hollywood'],
    'lifestylemarriage': ['lifestyle', 'marriage'],
    'finance-video': ['finance', 'video'],
    'halloween': ['halloween'],
    'entertainmenttv': ['entertainment', 'TV'],
    'lifestyledidyouknow': ['lifestyle', 'did', 'you', 'know'],
    'finance-saving-investing': ['finance', 'saving', 'investing'],
    'gaming': ['gaming'],
    'narendramodi_opinion': ['narendra', 'modi', 'opinion'],
    'healthyliving': ['healthy', 'living'],
    'nutrition': ['nutrition'],
    'movienews': ['movie', 'news'],
    'peopleandplaces': ['people', 'and', 'place'],
    'autosownership': ['auto', 'ownership'],
    'sports_news': ['sport', 'news'],
    'internationaltravel': ['international', 'travel'],
    'lifestyle-news-feature': ['lifestyle', 'news', 'feature'],
    'autospassenger': ['auto', 'passenger'],
    'lifestylesmartliving': ['lifestyle', 'smart', 'living'],
    'newscrime': ['news', 'crime'],
    'olympics-videos': ['Olympics', 'video'],
    'traveltrivia': ['travel', 'trivia'],
    'shop-apparel': ['shop', 'apparel'],
    'lifestyleroyals': ['lifestyle', 'royal'],
    'travel-adventure-travel': ['travel', 'adventure', 'travel'],
    'shop-all': ['shop', 'all'],
    'foodnews': ['food', 'news'],
    'baseball_mlb_videos': ['baseball', 'MLB', 'video'],
    'autosreview': ['auto', 'review'],
    'causes-environment': ['cause', 'environment'],
    'lifestylefamilyandrelationships': ['lifestyle', 'family', 'and', 'relationship'],
    'soccer_epl': ['soccer', 'EPL'],
    'football_ncaa': ['football', 'NCAA'],
    'more_sports': ['more', 'sport'],
    'newstrends': ['news', 'trend'],
    'watch': ['watch'],
    'newsnational': ['news', 'national'],
    'tunedin': ['tuned', 'in'],
    'movies-gallery': ['movie', 'gallery'],
    'finance-insidetheticker': ['finance', 'inside', 'the', 'ticker'],
    'boxing-mma': ['boxing', 'MMA'],
    'lifestyle': ['lifestyle'],
    'tvvideos': ['TV', 'video'],
    'personalfinance': ['personal', 'finance'],
    'boxing': ['boxing'],
    'soccer_mls': ['soccer', 'MLS'],
    'music-reviews': ['music', 'review'],
    'weightloss': ['weight', 'loss'],
    'lifestylehomeandgarden': ['lifestyle', 'home', 'and', 'garden'],
    'causes-green-living': ['cause', 'green', 'living'],
    'travelnews': ['travel', 'news'],
    'finance-savemoney': ['finance', 'savemoney'],
    'ads-lung-health': ['ads', 'lung', 'health'],
    'cooking': ['cooking'],
    'baseball': ['baseball'],
    'autoshybrids': ['auto', 'hybrid'],
    'celebritynews': ['celebrity', 'news'],
    'autosmotorcycles': ['auto', 'motorcycle'],
    'basketball_nba_videos': ['basketball', 'NBA', 'video'],
    'causes-disaster-relief': ['cause', 'disaster', 'relief'],
    'autosvideos': ['auto', 'video'],
    'basketball_ncaa': ['basketball', 'NCAA'],
    'seasonal': ['seasonal'],
    'musicvideos': ['music', 'video'],
    'lifestylehoroscopefish': ['lifestyle', 'horoscope', 'fish'],
    'autosvideonew': ['auto', 'video', 'new'],
    'autoscartech': ['auto', 'car', 'tech'],
    'awards': ['award'],
    'tv-golden-globes': ['TV', 'golden', 'globe'],
    'causes-animals': ['cause', 'animal'],
    'ustravel': ['US', 'travel'],
    'people-places': ['people', 'place'],
    'tennis': ['tennis'],
    'cardio': ['cardio'],
    'tipsandtricks': ['tip', 'and', 'trick'],
    'lifestylefashion': ['lifestyle', 'fashion'],
    'tv-golden-globes-video': ['TV', 'golden', 'globe', 'video'],
    'lifestyle-wedding': ['lifestyle', 'wedding'],
    'lifestylebeauty': ['lifestyle', 'beauty'],
    'newsvideos': ['news', 'video'],
    'weight-loss': ['weight', 'loss'],
    'downtime': ['downtime'],
    'finance-career': ['finance', 'career'],
    'health-news': ['health', 'news'],
    'recipes': ['recipe'],
    'lifestyleshopping': ['lifestyle', 'shopping'],
    'finance-auto-insurance': ['finance', 'auto', 'insurance'],
    'voices': ['voice'],
    'tv-gallery': ['TV', 'gallery']
}


cate_large_reset_dict = {
    'music': ['music'],
    'news': ['news'],
    'weather': ['weather'],
    'games': ['game'],
    'autos': ['auto'],
    'finance': ['finance'],
    'health': ['health'],
    'entertainment': ['entertainment'],
    'movies': ['movie'],
    'middleeast': ['middleeast'],
    'travel': ['travel'],
    'tv': ['TV'],
    'kids': ['kid'],
    'foodanddrink': ['food', 'and', 'drink'],
    'sports': ['sport'],
    'lifestyle': ['lifestyle'],
    'video': ['video'],
    'northamerica': ['northamerica']
}


subcate_large_reset_dict = {
    'ads-latingrammys': ['ads', 'latin', 'grammy'],
    'comedy': ['comedy'],
    'finance-real-estate': ['finance', 'real-estate'],
    'football_nfl_videos': ['football', 'NFL', 'video'],
    'humor': ['humor'],
    'lifestylerelationships': ['lifestyle', 'relationship'],
    'causes-poverty': ['cause', 'poverty'],
    'autosenthusiasts': ['auto', 'enthusiast'],
    'lifestylelovesex': ['lifestyle', 'love', 'sex'],
    'entertainmentmusic': ['entertainment', 'music'],
    'finance-companies': ['finance', 'company'],
    'golfvideos': ['golf', 'video'],
    'fitness': ['fitness'],
    'animals': ['animal'],
    'relationships': ['relationship'],
    'newsscience': ['news', 'science'],
    'wines': ['wine'],
    'empowering-the-planet': ['empowering', 'the', 'planet'],
    'topnews': ['top', 'news'],
    'basketball_nba': ['basketball', 'NBA'],
    'movies-awards': ['movie', 'award'],
    'foodtips': ['food', 'tip'],
    'newsus': ['news', 'US'],
    'finance-small-business': ['finance', 'small', 'business'],
    'finance-insurance': ['finance', 'insurance'],
    'finance-education': ['finance', 'education'],
    'shop-computers-electronics': ['shop', 'computer', 'electronic'],
    'lifestyletravel': ['lifestyle', 'travel'],
    'finance-billstopay': ['finance', 'bill', 'to', 'pay'],
    'lifestyleshoppinghomegarden': ['lifestyle', 'shopping', 'home', 'garden'],
    'lifestylestyle': ['lifestyle', 'style'],
    'finance-healthcare': ['finance', 'healthcare'],
    'autosluxury': ['auto', 'luxury'],
    'cookingschool': ['cooking', 'school'],
    'newsvideo': ['news', 'video'],
    'video': ['video'],
    'newsrealestate': ['news', 'real-estate'],
    'retirement': ['retirement'],
    'technologyinvesting': ['technology', 'investing'],
    'newsphotos': ['news', 'photo'],
    'lifestylecareer': ['lifestyle', 'career'],
    'newsoffbeat': ['news', 'offbeat'],
    'shop-home-goods': ['shop', 'home', 'goods'],
    'lifestylevideo': ['lifestyle', 'video'],
    'othersports': ['other', 'sport'],
    'spendingandborrowing': ['spending', 'and', 'borrowing'],
    'foodanddrink': ['food', 'and', 'drink'],
    'celebrity': ['celebrity'],
    'newsbusiness': ['news', 'business'],
    'causes-food-insecurity': ['cause', 'food', 'insecurity'],
    'racing': ['racing'],
    'lifestyleanimals': ['lifestyle', 'animal'],
    'yearinoffbeatgoodnews': ['year', 'in', 'offbeat', 'good', 'news'],
    'cma-awards': ['CMA', 'award'],
    'wellness': ['wellness'],
    'lifestylepets': ['lifestyle', 'pet'],
    'music-gallery': ['music', 'gallery'],
    'autostokyo': ['auto', 'tokyo'],
    'entertainment-books': ['entertainment', 'book'],
    'soccer': ['soccer'],
    'tv-reviews': ['TV', 'review'],
    'news': ['news'],
    'wonder': ['wonder'],
    'indepth': ['indepth'],
    'elections-2020-us': ['election', '2020', 'US'],
    'autoslosangeles': ['auto', 'los-angeles'],
    'travel-points-rewards': ['travel', 'point', 'reward'],
    'finance-taxes': ['finance', 'tax'],
    'music-grammys': ['music', 'grammy'],
    'pregnancyparenting': ['pregnancy', 'parenting'],
    'finance-career-education': ['finance', 'career', 'education'],
    'career-news': ['career', 'news'],
    'viral': ['viral'],
    'newstvmedia': ['news', 'TV', 'media'],
    'awardstyle': ['award', 'style'],
    'lifestylediy': ['lifestyle', 'DIY'],
    'newsother': ['news', 'other'],
    'football_nfl': ['football', 'NFL'],
    'movievideo': ['movie', 'video'],
    'basketball_ncaa_videos': ['basketball', 'NCAA', 'video'],
    'autosnews': ['auto', 'news'],
    'autosresearchguides': ['auto', 'research', 'guide'],
    'finance-startinvesting': ['finance', 'start', 'investing'],
    'celebhub': ['celeb', 'hub'],
    'movies-celebrity': ['movie', 'celebrity'],
    'finance-technology': ['finance', 'technology'],
    'football_ncaa_videos': ['football', 'NCAA', 'video'],
    'healthnews': ['health', 'news'],
    'newsworldpolitics': ['news', 'world', 'politics'],
    'company-news': ['company', 'news'],
    'newsgoodnews': ['news', 'good', 'news'],
    'science': ['science'],
    'sports': ['sport'],
    'financenews': ['finance', 'news'],
    'lifestyleweddings': ['lifestyle', 'wedding'],
    'newspolitics': ['news', 'politics'],
    'advice': ['advice'],
    'travelarticle': ['travel', 'article'],
    'cocktails': ['cocktail'],
    'finance-mutual-funds': ['finance', 'mutual', 'fund'],
    'music-awards': ['music', 'award'],
    'newsweather': ['news', 'weather'],
    'mentalhealth': ['mental', 'health'],
    'weatherfullscreenmaps': ['weather', 'full', 'screen', 'map'],
    'lifestylecelebstyle': ['lifestyle', 'celeb', 'style'],
    'autossuvs': ['auto', 'SUV'],
    'mma': ['MMA'],
    'games': ['game'],
    'health-cancer': ['health', 'cancer'],
    'tv-recaps': ['TV', 'recap'],
    'newsopinion': ['news', 'opinion'],
    'lifestylemindandsoul': ['lifestyle', 'mind', 'and', 'soul'],
    'popculture': ['pop', 'culture'],
    'entertainment-celebrity': ['entertainment', 'celebrity'],
    'autossports': ['auto', 'sport'],
    'finance-homesandpropertysection': ['finance', 'home', 'and', 'property', 'section'],
    'traveltips': ['travel', 'tip'],
    'holidays': ['holiday'],
    'newstechnology': ['news', 'technology'],
    'lifestylecleaningandorganizing': ['lifestyle', 'cleaning', 'and', 'organizing'],
    'foodrecipes': ['food', 'recipe'],
    'autosbuying': ['auto', 'buying'],
    'outdoors': ['outdoor'],
    'lifestylepetsanimals': ['lifestyle', 'pet', 'animal'],
    'fun': ['fun'],
    'medical': ['medical'],
    'traveltripideas': ['travel' ,'trip', 'idea'],
    'middleeast-top-stories': ['middleeast', 'top', 'story'],
    'restaurantsandnews': ['restaurant', 'and', 'news'],
    'golf': ['golf'],
    'lifestylebuzz': ['lifestyle', 'buzz'],
    'lifestylefamily': ['lifestyle', 'family'],
    'finance-home-loans': ['finance', 'home', 'loan'],
    'movies-oscars': ['movie', 'Oscars'],
    'lifestyleparenting': ['lifestyle', 'parenting'],
    'travel-videos': ['travel', 'video'],
    'finance-credit': ['finance', 'credit'],
    'basketball_wnba': ['basketball', 'WNBA'],
    'factcheck': ['factcheck'],
    'lifestylewhatshot': ['lifestyle', 'whats', 'hot'],
    'tv-celebrity': ['TV', 'celebrity'],
    'music-celebrity': ['music', 'celebrity'],
    'mmaufc': ['MMA', 'UFC'],
    'newsworld': ['news', 'world'],
    'musicnews': ['music', 'news'],
    'autosresearch': ['auto', 'research'],
    'autossema': ['auto', 'SEMA'],
    'northamerica-video': ['northamerica', 'video'],
    'finance-retirement': ['finance', 'retirement'],
    'causes-military-appreciation': ['cause', 'military', 'appreciation'],
    'healthagingwell': ['health', 'aging', 'well'],
    'tv': ['TV'],
    'markets': ['market'],
    'autoscompact': ['auto', 'compact'],
    'travel': ['travel'],
    'icehockey_nhl': ['ice', 'hockey', 'NHL'],
    'shop-holidays': ['shop', 'holiday'],
    'shop-books-movies-tv': ['shop', 'book', 'movie', 'TV'],
    'newselection2020': ['news', 'election', '2020'],
    'lifestylehoroscope': ['lifestyle', 'horoscope'],
    'tvnews': ['TV', 'news'],
    'newsscienceandtechnology': ['news', 'science', 'and', 'technology'],
    'finance-top-stocks': ['finance', 'top', 'stock'],
    'quickandeasy': ['quick', 'and', 'easy'],
    'autosclassics': ['auto', 'classic'],
    'autostrucks': ['auto', 'truck'],
    'autosvans': ['auto', 'van'],
    'strength': ['strength'],
    'causes': ['cause'],
    'videos': ['video'],
    'soccer_bund': ['soccer', 'bund'],
    'beverages': ['beverage'],
    'newsfactcheck': ['news', 'factcheck'],
    'reviews': ['review'],
    'games-news': ['game', 'news'],
    'photos': ['photo'],
    'autosmidsize': ['auto', 'midsize'],
    'lifestyledecor': ['lifestyle', 'decor'],
    'baseball_mlb': ['baseball', 'MLB'],
    'weathertopstories': ['weather', 'top', 'story'],
    'tennis_intl': ['tennis', 'INTL'],
    'hollywood': ['hollywood'],
    'lifestylemarriage': ['lifestyle', 'marriage'],
    'finance-video': ['finance', 'video'],
    'halloween': ['halloween'],
    'entertainmenttv': ['entertainment', 'TV'],
    'lifestyledidyouknow': ['lifestyle', 'did', 'you', 'know'],
    'finance-saving-investing': ['finance', 'saving', 'investing'],
    'gaming': ['gaming'],
    'narendramodi_opinion': ['narendra', 'modi', 'opinion'],
    'healthyliving': ['healthy', 'living'],
    'nutrition': ['nutrition'],
    'movienews': ['movie', 'news'],
    'peopleandplaces': ['people', 'and', 'place'],
    'autosownership': ['auto', 'ownership'],
    'sports_news': ['sport', 'news'],
    'internationaltravel': ['international', 'travel'],
    'lifestyle-news-feature': ['lifestyle', 'news', 'feature'],
    'autospassenger': ['auto', 'passenger'],
    'lifestylesmartliving': ['lifestyle', 'smart', 'living'],
    'newscrime': ['news', 'crime'],
    'olympics-videos': ['Olympics', 'video'],
    'traveltrivia': ['travel', 'trivia'],
    'shop-apparel': ['shop', 'apparel'],
    'lifestyleroyals': ['lifestyle', 'royal'],
    'travel-adventure-travel': ['travel', 'adventure', 'travel'],
    'shop-all': ['shop', 'all'],
    'foodnews': ['food', 'news'],
    'baseball_mlb_videos': ['baseball', 'MLB', 'video'],
    'autosreview': ['auto', 'review'],
    'causes-environment': ['cause', 'environment'],
    'lifestylefamilyandrelationships': ['lifestyle', 'family', 'and', 'relationship'],
    'soccer_epl': ['soccer', 'EPL'],
    'football_ncaa': ['football', 'NCAA'],
    'more_sports': ['more', 'sport'],
    'newstrends': ['news', 'trend'],
    'watch': ['watch'],
    'newsnational': ['news', 'national'],
    'tunedin': ['tuned'],
    'movies-gallery': ['movie', 'gallery'],
    'finance-insidetheticker': ['finance', 'inside', 'the', 'ticker'],
    'boxing-mma': ['boxing', 'MMA'],
    'lifestyle': ['lifestyle'],
    'tvvideos': ['TV', 'video'],
    'personalfinance': ['personal', 'finance'],
    'boxing': ['boxing'],
    'soccer_mls': ['soccer', 'MLS'],
    'music-reviews': ['music', 'review'],
    'weightloss': ['weight', 'loss'],
    'lifestylehomeandgarden': ['lifestyle', 'home', 'and', 'garden'],
    'causes-green-living': ['cause', 'green', 'living'],
    'travelnews': ['travel', 'news'],
    'finance-savemoney': ['finance', 'savemoney'],
    'ads-lung-health': ['ads', 'lung', 'health'],
    'cooking': ['cooking'],
    'baseball': ['baseball'],
    'autoshybrids': ['auto', 'hybrid'],
    'celebritynews': ['celebrity', 'news'],
    'autosmotorcycles': ['auto', 'motorcycle'],
    'basketball_nba_videos': ['basketball', 'NBA', 'video'],
    'causes-disaster-relief': ['cause', 'disaster', 'relief'],
    'autosvideos': ['auto', 'video'],
    'basketball_ncaa': ['basketball', 'NCAA'],
    'seasonal': ['seasonal'],
    'musicvideos': ['music', 'video'],
    'lifestylehoroscopefish': ['lifestyle', 'horoscope', 'fish'],
    'autosvideonew': ['auto', 'video', 'new'],
    'autoscartech': ['auto', 'car', 'tech'],
    'awards': ['award'],
    'tv-golden-globes': ['TV', 'golden', 'globe'],
    'causes-animals': ['cause', 'animal'],
    'ustravel': ['US', 'travel'],
    'people-places': ['people', 'place'],
    'tennis': ['tennis'],
    'cardio': ['cardio'],
    'tipsandtricks': ['tip', 'and', 'trick'],
    'lifestylefashion': ['lifestyle', 'fashion'],
    'tv-golden-globes-video': ['TV', 'golden', 'globe', 'video'],
    'lifestyle-wedding': ['lifestyle', 'wedding'],
    'lifestylebeauty': ['lifestyle', 'beauty'],
    'newsvideos': ['news', 'video'],
    'weight-loss': ['weight', 'loss'],
    'downtime': ['downtime'],
    'finance-career': ['finance', 'career'],
    'health-news': ['health', 'news'],
    'recipes': ['recipe'],
    'lifestyleshopping': ['lifestyle', 'shopping'],
    'finance-auto-insurance': ['finance', 'auto', 'insurance'],
    'voices': ['voice'],
    'tv-gallery': ['TV', 'gallery'],
    "shop-toys": ['shop', 'toy'],
    "newslocalpolitics": ['news', 'local', 'politics'],
    "technology": ['technology'],
    "localnews": ['local', 'news'],
    "mindandbody": ['mind', 'and', 'body'],
    "finance-savingsrates": ['finance', 'saving', 'rate'],
    "seasonalvideos": ['seasonal', 'video'],
    "soccer_fifa_wwc": ['soccer', 'FIFA', 'WWC'],
    "style": ['style'],
    "healthandfitness": ['health', 'and', 'fitness'],
    "lifestyledesign": ['lifestyle', 'design'],
    "opinion-polls": ['opinion', 'poll'],
    "grammys-video": ['grammy', 'video'],
    "familyhealth": ['family', 'health'],
    "travel-accessible": ['travel', 'accessible'],
    "autosconvertibles": ['auto', 'convertible'],
    "other": ['other'],
    "foodvideos": ['food', 'video'],
    "basketball": ['basketball'],
    "healthtrending": ['health', 'trending'],
    "soccer_videos": ['soccer', 'video'],
    "causes-gender-equality": ['cause', 'gender', 'equality'],
    "smartliving": ['smart', 'living']
}
