bert_path = "/data/nlp/jiangjx/nlp/bert/bert_base_uncased/"


cate_small_reset_dict = {
    'music': ['music'],
    'lifestyle': ['lifestyle'],
    'autos': ['autos'],
    'middleeast': ['middleeast'],
    'games': ['games'],
    'movies': ['movies'],
    'northamerica': ['northamerica'],
    'weather': ['weather'],
    'sports': ['sports'],
    'travel': ['travel'],
    'tv': ['tv'],
    'finance': ['finance'],
    'foodanddrink': ['food', 'drink'],
    'kids': ['kids'],
    'video': ['video'],
    'health': ['health'],
    'news': ['news'],
    'entertainment': ['entertainment']
}


subcate_small_reset_dict = {
    'ads-latingrammys': ['ads', 'latin', 'grammys'],
    'comedy': ['comedy'],
    'finance-real-estate': ['finance', 'real-estate'],
    'football_nfl_videos': ['football', 'NFL', 'videos'],
    'humor': ['humor'],
    'lifestylerelationships': ['lifestyle', 'relationships'],
    'causes-poverty': ['causes', 'poverty'],
    'autosenthusiasts': ['autos', 'enthusiasts'],
    'lifestylelovesex': ['lifestyle', 'love', 'sex'],
    'entertainmentmusic': ['entertainment', 'music'],
    'finance-companies': ['finance', 'companies'],
    'golfvideos': ['golf', 'videos'],
    'fitness': ['fitness'],
    'animals': ['animals'],
    'relationships': ['relationships'],
    'newsscience': ['news', 'science'],
    'wines': ['wines'],
    'empowering-the-planet': ['empowering', 'planet'],
    'topnews': ['topnews'],
    'basketball_nba': ['basketball', 'NBA'],
    'movies-awards': ['movies', 'awards'],
    'foodtips': ['food', 'tips'],
    'newsus': ['news', 'US'],
    'finance-small-business': ['finance', 'small', 'business'],
    'finance-insurance': ['finance', 'insurance'],
    'finance-education': ['finance', 'education'],
    'shop-computers-electronics': ['shop', 'computers', 'electronics'],
    'lifestyletravel': ['lifestyle', 'travel'],
    'finance-billstopay': ['finance', 'bills', 'pay'],
    'lifestyleshoppinghomegarden': ['lifestyle', 'shopping', 'home', 'garden'],
    'lifestylestyle': ['lifestyle', 'style'],
    'finance-healthcare': ['finance', 'healthcare'],
    'autosluxury': ['autos', 'luxury'],
    'cookingschool': ['cooking', 'school'],
    'newsvideo': ['news', 'video'],
    'video': ['video'],
    'newsrealestate': ['news', 'real-estate'],
    'retirement': ['retirement'],
    'technologyinvesting': ['technology', 'investing'],
    'newsphotos': ['news', 'photos'],
    'lifestylecareer': ['lifestyle', 'career'],
    'newsoffbeat': ['news', 'offbeat'],
    'shop-home-goods': ['shop', 'home', 'goods'],
    'lifestylevideo': ['lifestyle', 'video'],
    'othersports': ['other', 'sports'],
    'spendingandborrowing': ['spending', 'borrowing'],
    'foodanddrink': ['food', 'drink'],
    'celebrity': ['celebrity'],
    'newsbusiness': ['news', 'business'],
    'causes-food-insecurity': ['causes', 'food', 'insecurity'],
    'racing': ['racing'],
    'lifestyleanimals': ['lifestyle', 'animals'],
    'yearinoffbeatgoodnews': ['year', 'offbeat', 'good', 'news'],
    'cma-awards': ['CMA', 'awards'],
    'wellness': ['wellness'],
    'lifestylepets': ['lifestyle', 'pets'],
    'music-gallery': ['music', 'gallery'],
    'autostokyo': ['autos', 'tokyo'],
    'entertainment-books': ['entertainment', 'books'],
    'soccer': ['soccer'],
    'tv-reviews': ['tv', 'reviews'],
    'news': ['news'],
    'wonder': ['wonder'],
    'indepth': ['indepth'],
    'elections-2020-us': ['elections', '2020', 'US'],
    'autoslosangeles': ['autos', 'los-angeles'],
    'travel-points-rewards': ['travel', 'points', 'rewards'],
    'finance-taxes': ['finance', 'taxes'],
    'music-grammys': ['music', 'grammys'],
    'pregnancyparenting': ['pregnancy', 'parenting'],
    'finance-career-education': ['finance', 'career', 'education'],
    'career-news': ['career', 'news'],
    'viral': ['viral'],
    'newstvmedia': ['news', 'tv', 'media'],
    'awardstyle': ['award', 'style'],
    'lifestylediy': ['lifestyle', 'diy'],
    'newsother': ['news', 'other'],
    'football_nfl': ['football', 'NFL'],
    'movievideo': ['movie', 'video'],
    'basketball_ncaa_videos': ['basketball', 'NCAA', 'videos'],
    'autosnews': ['autos', 'news'],
    'autosresearchguides': ['autos', 'research', 'guides'],
    'finance-startinvesting': ['finance', 'start', 'investing'],
    'celebhub': ['celeb', 'hub'],
    'movies-celebrity': ['movies', 'celebrity'],
    'finance-technology': ['finance', 'technology'],
    'football_ncaa_videos': ['football', 'NCAA', 'videos'],
    'healthnews': ['health', 'news'],
    'newsworldpolitics': ['news', 'world', 'politics'],
    'company-news': ['company', 'news'],
    'newsgoodnews': ['news', 'good', 'news'],
    'science': ['science'],
    'sports': ['sports'],
    'financenews': ['finance', 'news'],
    'lifestyleweddings': ['lifestyle', 'weddings'],
    'newspolitics': ['news', 'politics'],
    'advice': ['advice'],
    'travelarticle': ['travel', 'article'],
    'cocktails': ['cocktails'],
    'finance-mutual-funds': ['finance', 'mutual', 'funds'],
    'music-awards': ['music', 'awards'],
    'newsweather': ['news', 'weather'],
    'mentalhealth': ['mental', 'health'],
    'weatherfullscreenmaps': ['weather', 'full', 'screen', 'maps'],
    'lifestylecelebstyle': ['lifestyle', 'celeb', 'style'],
    'autossuvs': ['autos', 'suvs'],
    'mma': ['MMA'],
    'games': ['games'],
    'health-cancer': ['health', 'cancer'],
    'tv-recaps': ['tv', 'recaps'],
    'newsopinion': ['news', 'opinion'],
    'lifestylemindandsoul': ['lifestyle', 'mind', 'soul'],
    'popculture': ['pop', 'culture'],
    'entertainment-celebrity': ['entertainment', 'celebrity'],
    'autossports': ['autos', 'sports'],
    'finance-homesandpropertysection': ['finance', 'homes', 'property', 'section'],
    'traveltips': ['travel', 'tips'],
    'holidays': ['holidays'],
    'newstechnology': ['news', 'technology'],
    'lifestylecleaningandorganizing': ['lifestyle', 'cleaning', 'organizing'],
    'foodrecipes': ['food', 'recipes'],
    'autosbuying': ['autos', 'buying'],
    'outdoors': ['outdoors'],
    'lifestylepetsanimals': ['lifestyle', 'pets', 'animals'],
    'fun': ['fun'],
    'medical': ['medical'],
    'traveltripideas': ['travel' ,'trip', 'ideas'],
    'middleeast-top-stories': ['middleeast', 'top', 'stories'],
    'restaurantsandnews': ['restaurant', 'sand', 'news'],
    'golf': ['golf'],
    'lifestylebuzz': ['lifestyle', 'buzz'],
    'lifestylefamily': ['lifestyle', 'family'],
    'finance-home-loans': ['finance', 'home', 'loans'],
    'movies-oscars': ['movies', 'oscars'],
    'lifestyleparenting': ['lifestyle', 'parenting'],
    'travel-videos': ['travel', 'videos'],
    'finance-credit': ['finance', 'credit'],
    'basketball_wnba': ['basketball', 'WNBA'],
    'factcheck': ['factcheck'],
    'lifestylewhatshot': ['lifestyle', 'whats', 'hot'],
    'tv-celebrity': ['tv', 'celebrity'],
    'music-celebrity': ['music', 'celebrity'],
    'mmaufc': ['mma', 'UFC'],
    'newsworld': ['news', 'world'],
    'musicnews': ['music', 'news'],
    'autosresearch': ['autos', 'research'],
    'autossema': ['autos', 'sema'],
    'northamerica-video': ['north', 'america', 'video'],
    'finance-retirement': ['finance', 'retirement'],
    'causes-military-appreciation': ['causes', 'military', 'appreciation'],
    'healthagingwell': ['health', 'aging', 'well'],
    'tv': ['tv'],
    'markets': ['markets'],
    'autoscompact': ['autos', 'compact'],
    'travel': ['travel'],
    'icehockey_nhl': ['ice', 'hockey', 'NHL'],
    'shop-holidays': ['shop', 'holidays'],
    'shop-books-movies-tv': ['shop', 'books', 'movies', 'tv'],
    'newselection2020': ['news', 'election', '2020'],
    'lifestylehoroscope': ['lifestyle', 'horoscope'],
    'tvnews': ['tv', 'news'],
    'newsscienceandtechnology': ['news', 'science', 'technology'],
    'finance-top-stocks': ['finance', 'top', 'stocks'],
    'quickandeasy': ['quick', 'easy'],
    'autosclassics': ['autos', 'classics'],
    'autostrucks': ['autos', 'trucks'],
    'autosvans': ['autos', 'vans'],
    'strength': ['strength'],
    'causes': ['causes'],
    'videos': ['videos'],
    'soccer_bund': ['soccer', 'bund'],
    'beverages': ['beverages'],
    'newsfactcheck': ['news', 'factcheck'],
    'reviews': ['reviews'],
    'games-news': ['games', 'news'],
    'photos': ['photos'],
    'autosmidsize': ['autos', 'midsize'],
    'lifestyledecor': ['lifestyle', 'decor'],
    'baseball_mlb': ['baseball', 'MLB'],
    'weathertopstories': ['weather', 'top', 'stories'],
    'tennis_intl': ['tennis', 'INTL'],
    'hollywood': ['hollywood'],
    'lifestylemarriage': ['lifestyle', 'marriage'],
    'finance-video': ['finance', 'video'],
    'halloween': ['halloween'],
    'entertainmenttv': ['entertainment', 'tv'],
    'lifestyledidyouknow': ['lifestyle', 'did', 'you', 'know'],
    'finance-saving-investing': ['finance', 'saving', 'investing'],
    'gaming': ['gaming'],
    'narendramodi_opinion': ['narendra', 'modi', 'opinion'],
    'healthyliving': ['healthy', 'living'],
    'nutrition': ['nutrition'],
    'movienews': ['movie', 'news'],
    'peopleandplaces': ['people', 'places'],
    'autosownership': ['autos', 'ownership'],
    'sports_news': ['sports', 'news'],
    'internationaltravel': ['international', 'travel'],
    'lifestyle-news-feature': ['lifestyle', 'news', 'feature'],
    'autospassenger': ['autos', 'passenger'],
    'lifestylesmartliving': ['lifestyle', 'smart', 'living'],
    'newscrime': ['news', 'crime'],
    'olympics-videos': ['olympics', 'videos'],
    'traveltrivia': ['travel', 'trivia'],
    'shop-apparel': ['shop', 'apparel'],
    'lifestyleroyals': ['lifestyle', 'royals'],
    'travel-adventure-travel': ['travel', 'adventure', 'travel'],
    'shop-all': ['shop', 'all'],
    'foodnews': ['food', 'news'],
    'baseball_mlb_videos': ['baseball', 'MLB', 'videos'],
    'autosreview': ['autos', 'review'],
    'causes-environment': ['causes', 'environment'],
    'lifestylefamilyandrelationships': ['lifestyle', 'family', 'relationships'],
    'soccer_epl': ['soccer', 'EPL'],
    'football_ncaa': ['football', 'NCAA'],
    'more_sports': ['more', 'sports'],
    'newstrends': ['news', 'trends'],
    'watch': ['watch'],
    'newsnational': ['news', 'national'],
    'tunedin': ['tuned'],
    'movies-gallery': ['movies', 'gallery'],
    'finance-insidetheticker': ['finance', 'inside', 'ticker'],
    'boxing-mma': ['boxing', 'MMA'],
    'lifestyle': ['lifestyle'],
    'tvvideos': ['tv', 'videos'],
    'personalfinance': ['personal', 'finance'],
    'boxing': ['boxing'],
    'soccer_mls': ['soccer', 'MLS'],
    'music-reviews': ['music', 'reviews'],
    'weightloss': ['weight', 'loss'],
    'lifestylehomeandgarden': ['lifestyle', 'home', 'garden'],
    'causes-green-living': ['causes', 'green', 'living'],
    'travelnews': ['travel', 'news'],
    'finance-savemoney': ['finance', 'savemoney'],
    'ads-lung-health': ['ads', 'lung', 'health'],
    'cooking': ['cooking'],
    'baseball': ['baseball'],
    'autoshybrids': ['autos', 'hybrids'],
    'celebritynews': ['celebrity', 'news'],
    'autosmotorcycles': ['autos', 'motorcycles'],
    'basketball_nba_videos': ['basketball', 'NBA', 'videos'],
    'causes-disaster-relief': ['causes', 'disaster', 'relief'],
    'autosvideos': ['autos', 'videos'],
    'basketball_ncaa': ['basketball', 'NCAA'],
    'seasonal': ['seasonal'],
    'musicvideos': ['music', 'videos'],
    'lifestylehoroscopefish': ['lifestyle', 'horoscope', 'fish'],
    'autosvideonew': ['autos', 'video', 'new'],
    'autoscartech': ['autos', 'car', 'tech'],
    'awards': ['awards'],
    'tv-golden-globes': ['tv', 'golden', 'globes'],
    'causes-animals': ['causes', 'animals'],
    'ustravel': ['US', 'travel'],
    'people-places': ['people', 'places'],
    'tennis': ['tennis'],
    'cardio': ['cardio'],
    'tipsandtricks': ['tips', 'tricks'],
    'lifestylefashion': ['lifestyle', 'fashion'],
    'tv-golden-globes-video': ['tv', 'golden', 'globes', 'video'],
    'lifestyle-wedding': ['lifestyle', 'wedding'],
    'lifestylebeauty': ['lifestyle', 'beauty'],
    'newsvideos': ['news', 'videos'],
    'weight-loss': ['weight', 'loss'],
    'downtime': ['downtime'],
    'finance-career': ['finance', 'career'],
    'health-news': ['health', 'news'],
    'recipes': ['recipes'],
    'lifestyleshopping': ['lifestyle', 'shopping'],
    'finance-auto-insurance': ['finance', 'auto', 'insurance'],
    'voices': ['voices'],
    'tv-gallery': ['tv', 'gallery']
}


subcate_large_reset_dict = {
    'ads-latingrammys': ['ads', 'latin', 'grammys'],
    'comedy': ['comedy'],
    'finance-real-estate': ['finance', 'real-estate'],
    'football_nfl_videos': ['football', 'NFL', 'videos'],
    'humor': ['humor'],
    'lifestylerelationships': ['lifestyle', 'relationships'],
    'causes-poverty': ['causes', 'poverty'],
    'autosenthusiasts': ['autos', 'enthusiasts'],
    'lifestylelovesex': ['lifestyle', 'love', 'sex'],
    'entertainmentmusic': ['entertainment', 'music'],
    'finance-companies': ['finance', 'companies'],
    'golfvideos': ['golf', 'videos'],
    'fitness': ['fitness'],
    'animals': ['animals'],
    'relationships': ['relationships'],
    'newsscience': ['news', 'science'],
    'wines': ['wines'],
    'empowering-the-planet': ['empowering', 'planet'],
    'topnews': ['topnews'],
    'basketball_nba': ['basketball', 'NBA'],
    'movies-awards': ['movies', 'awards'],
    'foodtips': ['food', 'tips'],
    'newsus': ['news', 'US'],
    'finance-small-business': ['finance', 'small', 'business'],
    'finance-insurance': ['finance', 'insurance'],
    'finance-education': ['finance', 'education'],
    'shop-computers-electronics': ['shop', 'computers', 'electronics'],
    'lifestyletravel': ['lifestyle', 'travel'],
    'finance-billstopay': ['finance', 'bills', 'pay'],
    'lifestyleshoppinghomegarden': ['lifestyle', 'shopping', 'home', 'garden'],
    'lifestylestyle': ['lifestyle', 'style'],
    'finance-healthcare': ['finance', 'healthcare'],
    'autosluxury': ['autos', 'luxury'],
    'cookingschool': ['cooking', 'school'],
    'newsvideo': ['news', 'video'],
    'video': ['video'],
    'newsrealestate': ['news', 'real-estate'],
    'retirement': ['retirement'],
    'technologyinvesting': ['technology', 'investing'],
    'newsphotos': ['news', 'photos'],
    'lifestylecareer': ['lifestyle', 'career'],
    'newsoffbeat': ['news', 'offbeat'],
    'shop-home-goods': ['shop', 'home', 'goods'],
    'lifestylevideo': ['lifestyle', 'video'],
    'othersports': ['other', 'sports'],
    'spendingandborrowing': ['spending', 'borrowing'],
    'foodanddrink': ['food', 'drink'],
    'celebrity': ['celebrity'],
    'newsbusiness': ['news', 'business'],
    'causes-food-insecurity': ['causes', 'food', 'insecurity'],
    'racing': ['racing'],
    'lifestyleanimals': ['lifestyle', 'animals'],
    'yearinoffbeatgoodnews': ['year', 'offbeat', 'good', 'news'],
    'cma-awards': ['CMA', 'awards'],
    'wellness': ['wellness'],
    'lifestylepets': ['lifestyle', 'pets'],
    'music-gallery': ['music', 'gallery'],
    'autostokyo': ['autos', 'tokyo'],
    'entertainment-books': ['entertainment', 'books'],
    'soccer': ['soccer'],
    'tv-reviews': ['tv', 'reviews'],
    'news': ['news'],
    'wonder': ['wonder'],
    'indepth': ['indepth'],
    'elections-2020-us': ['elections', '2020', 'US'],
    'autoslosangeles': ['autos', 'los-angeles'],
    'travel-points-rewards': ['travel', 'points', 'rewards'],
    'finance-taxes': ['finance', 'taxes'],
    'music-grammys': ['music', 'grammys'],
    'pregnancyparenting': ['pregnancy', 'parenting'],
    'finance-career-education': ['finance', 'career', 'education'],
    'career-news': ['career', 'news'],
    'viral': ['viral'],
    'newstvmedia': ['news', 'tv', 'media'],
    'awardstyle': ['award', 'style'],
    'lifestylediy': ['lifestyle', 'diy'],
    'newsother': ['news', 'other'],
    'football_nfl': ['football', 'NFL'],
    'movievideo': ['movie', 'video'],
    'basketball_ncaa_videos': ['basketball', 'NCAA', 'videos'],
    'autosnews': ['autos', 'news'],
    'autosresearchguides': ['autos', 'research', 'guides'],
    'finance-startinvesting': ['finance', 'start', 'investing'],
    'celebhub': ['celeb', 'hub'],
    'movies-celebrity': ['movies', 'celebrity'],
    'finance-technology': ['finance', 'technology'],
    'football_ncaa_videos': ['football', 'NCAA', 'videos'],
    'healthnews': ['health', 'news'],
    'newsworldpolitics': ['news', 'world', 'politics'],
    'company-news': ['company', 'news'],
    'newsgoodnews': ['news', 'good', 'news'],
    'science': ['science'],
    'sports': ['sports'],
    'financenews': ['finance', 'news'],
    'lifestyleweddings': ['lifestyle', 'weddings'],
    'newspolitics': ['news', 'politics'],
    'advice': ['advice'],
    'travelarticle': ['travel', 'article'],
    'cocktails': ['cocktails'],
    'finance-mutual-funds': ['finance', 'mutual', 'funds'],
    'music-awards': ['music', 'awards'],
    'newsweather': ['news', 'weather'],
    'mentalhealth': ['mental', 'health'],
    'weatherfullscreenmaps': ['weather', 'full', 'screen', 'maps'],
    'lifestylecelebstyle': ['lifestyle', 'celeb', 'style'],
    'autossuvs': ['autos', 'suvs'],
    'mma': ['MMA'],
    'games': ['games'],
    'health-cancer': ['health', 'cancer'],
    'tv-recaps': ['tv', 'recaps'],
    'newsopinion': ['news', 'opinion'],
    'lifestylemindandsoul': ['lifestyle', 'mind', 'soul'],
    'popculture': ['pop', 'culture'],
    'entertainment-celebrity': ['entertainment', 'celebrity'],
    'autossports': ['autos', 'sports'],
    'finance-homesandpropertysection': ['finance', 'homes', 'property', 'section'],
    'traveltips': ['travel', 'tips'],
    'holidays': ['holidays'],
    'newstechnology': ['news', 'technology'],
    'lifestylecleaningandorganizing': ['lifestyle', 'cleaning', 'organizing'],
    'foodrecipes': ['food', 'recipes'],
    'autosbuying': ['autos', 'buying'],
    'outdoors': ['outdoors'],
    'lifestylepetsanimals': ['lifestyle', 'pets', 'animals'],
    'fun': ['fun'],
    'medical': ['medical'],
    'traveltripideas': ['travel' ,'trip', 'ideas'],
    'middleeast-top-stories': ['middleeast', 'top', 'stories'],
    'restaurantsandnews': ['restaurant', 'sand', 'news'],
    'golf': ['golf'],
    'lifestylebuzz': ['lifestyle', 'buzz'],
    'lifestylefamily': ['lifestyle', 'family'],
    'finance-home-loans': ['finance', 'home', 'loans'],
    'movies-oscars': ['movies', 'oscars'],
    'lifestyleparenting': ['lifestyle', 'parenting'],
    'travel-videos': ['travel', 'videos'],
    'finance-credit': ['finance', 'credit'],
    'basketball_wnba': ['basketball', 'WNBA'],
    'factcheck': ['factcheck'],
    'lifestylewhatshot': ['lifestyle', 'whats', 'hot'],
    'tv-celebrity': ['tv', 'celebrity'],
    'music-celebrity': ['music', 'celebrity'],
    'mmaufc': ['mma', 'UFC'],
    'newsworld': ['news', 'world'],
    'musicnews': ['music', 'news'],
    'autosresearch': ['autos', 'research'],
    'autossema': ['autos', 'sema'],
    'northamerica-video': ['north', 'america', 'video'],
    'finance-retirement': ['finance', 'retirement'],
    'causes-military-appreciation': ['causes', 'military', 'appreciation'],
    'healthagingwell': ['health', 'aging', 'well'],
    'tv': ['tv'],
    'markets': ['markets'],
    'autoscompact': ['autos', 'compact'],
    'travel': ['travel'],
    'icehockey_nhl': ['ice', 'hockey', 'NHL'],
    'shop-holidays': ['shop', 'holidays'],
    'shop-books-movies-tv': ['shop', 'books', 'movies', 'tv'],
    'newselection2020': ['news', 'election', '2020'],
    'lifestylehoroscope': ['lifestyle', 'horoscope'],
    'tvnews': ['tv', 'news'],
    'newsscienceandtechnology': ['news', 'science', 'technology'],
    'finance-top-stocks': ['finance', 'top', 'stocks'],
    'quickandeasy': ['quick', 'easy'],
    'autosclassics': ['autos', 'classics'],
    'autostrucks': ['autos', 'trucks'],
    'autosvans': ['autos', 'vans'],
    'strength': ['strength'],
    'causes': ['causes'],
    'videos': ['videos'],
    'soccer_bund': ['soccer', 'bund'],
    'beverages': ['beverages'],
    'newsfactcheck': ['news', 'factcheck'],
    'reviews': ['reviews'],
    'games-news': ['games', 'news'],
    'photos': ['photos'],
    'autosmidsize': ['autos', 'midsize'],
    'lifestyledecor': ['lifestyle', 'decor'],
    'baseball_mlb': ['baseball', 'MLB'],
    'weathertopstories': ['weather', 'top', 'stories'],
    'tennis_intl': ['tennis', 'INTL'],
    'hollywood': ['hollywood'],
    'lifestylemarriage': ['lifestyle', 'marriage'],
    'finance-video': ['finance', 'video'],
    'halloween': ['halloween'],
    'entertainmenttv': ['entertainment', 'tv'],
    'lifestyledidyouknow': ['lifestyle', 'did', 'you', 'know'],
    'finance-saving-investing': ['finance', 'saving', 'investing'],
    'gaming': ['gaming'],
    'narendramodi_opinion': ['narendra', 'modi', 'opinion'],
    'healthyliving': ['healthy', 'living'],
    'nutrition': ['nutrition'],
    'movienews': ['movie', 'news'],
    'peopleandplaces': ['people', 'places'],
    'autosownership': ['autos', 'ownership'],
    'sports_news': ['sports', 'news'],
    'internationaltravel': ['international', 'travel'],
    'lifestyle-news-feature': ['lifestyle', 'news', 'feature'],
    'autospassenger': ['autos', 'passenger'],
    'lifestylesmartliving': ['lifestyle', 'smart', 'living'],
    'newscrime': ['news', 'crime'],
    'olympics-videos': ['olympics', 'videos'],
    'traveltrivia': ['travel', 'trivia'],
    'shop-apparel': ['shop', 'apparel'],
    'lifestyleroyals': ['lifestyle', 'royals'],
    'travel-adventure-travel': ['travel', 'adventure', 'travel'],
    'shop-all': ['shop', 'all'],
    'foodnews': ['food', 'news'],
    'baseball_mlb_videos': ['baseball', 'MLB', 'videos'],
    'autosreview': ['autos', 'review'],
    'causes-environment': ['causes', 'environment'],
    'lifestylefamilyandrelationships': ['lifestyle', 'family', 'relationships'],
    'soccer_epl': ['soccer', 'EPL'],
    'football_ncaa': ['football', 'NCAA'],
    'more_sports': ['more', 'sports'],
    'newstrends': ['news', 'trends'],
    'watch': ['watch'],
    'newsnational': ['news', 'national'],
    'tunedin': ['tuned'],
    'movies-gallery': ['movies', 'gallery'],
    'finance-insidetheticker': ['finance', 'inside', 'ticker'],
    'boxing-mma': ['boxing', 'MMA'],
    'lifestyle': ['lifestyle'],
    'tvvideos': ['tv', 'videos'],
    'personalfinance': ['personal', 'finance'],
    'boxing': ['boxing'],
    'soccer_mls': ['soccer', 'MLS'],
    'music-reviews': ['music', 'reviews'],
    'weightloss': ['weight', 'loss'],
    'lifestylehomeandgarden': ['lifestyle', 'home', 'garden'],
    'causes-green-living': ['causes', 'green', 'living'],
    'travelnews': ['travel', 'news'],
    'finance-savemoney': ['finance', 'savemoney'],
    'ads-lung-health': ['ads', 'lung', 'health'],
    'cooking': ['cooking'],
    'baseball': ['baseball'],
    'autoshybrids': ['autos', 'hybrids'],
    'celebritynews': ['celebrity', 'news'],
    'autosmotorcycles': ['autos', 'motorcycles'],
    'basketball_nba_videos': ['basketball', 'NBA', 'videos'],
    'causes-disaster-relief': ['causes', 'disaster', 'relief'],
    'autosvideos': ['autos', 'videos'],
    'basketball_ncaa': ['basketball', 'NCAA'],
    'seasonal': ['seasonal'],
    'musicvideos': ['music', 'videos'],
    'lifestylehoroscopefish': ['lifestyle', 'horoscope', 'fish'],
    'autosvideonew': ['autos', 'video', 'new'],
    'autoscartech': ['autos', 'car', 'tech'],
    'awards': ['awards'],
    'tv-golden-globes': ['tv', 'golden', 'globes'],
    'causes-animals': ['causes', 'animals'],
    'ustravel': ['US', 'travel'],
    'people-places': ['people', 'places'],
    'tennis': ['tennis'],
    'cardio': ['cardio'],
    'tipsandtricks': ['tips', 'tricks'],
    'lifestylefashion': ['lifestyle', 'fashion'],
    'tv-golden-globes-video': ['tv', 'golden', 'globes', 'video'],
    'lifestyle-wedding': ['lifestyle', 'wedding'],
    'lifestylebeauty': ['lifestyle', 'beauty'],
    'newsvideos': ['news', 'videos'],
    'weight-loss': ['weight', 'loss'],
    'downtime': ['downtime'],
    'finance-career': ['finance', 'career'],
    'health-news': ['health', 'news'],
    'recipes': ['recipes'],
    'lifestyleshopping': ['lifestyle', 'shopping'],
    'finance-auto-insurance': ['finance', 'auto', 'insurance'],
    'voices': ['voices'],
    'tv-gallery': ['tv', 'gallery'],
    "shop-toys": ['shop', 'toys'],
    "newslocalpolitics": ['news', 'local', 'politics'],
    "technology": ['technology'],
    "localnews": ['local', 'news'],
    "mindandbody": ['mind', 'body'],
    "finance-savingsrates": ['finance', 'savings', 'rates'],
    "seasonalvideos": ['seasonal', 'videos'],
    "soccer_fifa_wwc": ['soccer', 'FIFA', 'WWC'],
    "style": ['style'],
    "healthandfitness": ['health', 'fitness'],
    "lifestyledesign": ['lifestyle', 'design'],
    "opinion-polls": ['opinion', 'polls'],
    "grammys-video": ['grammys', 'video'],
    "familyhealth": ['family', 'health'],
    "travel-accessible": ['travel', 'accessible'],
    "autosconvertibles": ['autos', 'convertibles'],
    "other": ['other'],
    "foodvideos": ['food', 'videos'],
    "basketball": ['basketball'],
    "healthtrending": ['health', 'trending'],
    "soccer_videos": ['soccer', 'videos'],
    "causes-gender-equality": ['causes', 'gender', 'equality'],
    "smartliving": ['smart', 'living']
}